name: Basic workflow

on:
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Display Hello World
      run: echo "Hello, World!"

  deploy-in-dev:
    needs: deploy 
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Create Resource Group
      run: |
        az group create --name rg-dev --location eastus

  deploy-in-nonprd:
    needs: deploy-in-dev
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Create Resource Group
      run: |
        az group create --name rg-nonprd --location eastus

  deploy-in-prd:
    needs: deploy-in-nonprd
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Create Resource Group
      run: |
        az group create --name rg-prd --location eastus
